name: build and push image to docker to Docker Hub

on:
    push:
        branches:
            - master
    pull requests:
        branches:
            - master        


jobs:
    build:
        runs on: ubuntu-latest
        steps:
            - name: Checkout
             uses: actions/checkout@V2
            - name: setup php:8.1
             uses: shivammatur/setup-php@v2

            - name: Build the Docker image
              run: docker build -t kinglivail/file:1 .
              run: docker push kinglivail/file:1

